wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1650692956
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 17
      4: 3.6.13
      5: 0.12.15
      8:
      - 5
